function callbackToAddFunctions(objs, newFunctions)

    % The idea is to replace the existing callback with a line that calls
    % the existing callback and then calls the functions in newFunctions as
    % well.
    for i = 1:length(objs)
    set(objs(i), 'Callback', @(h,e)(cellfun(@(x)feval(x,h,e), ...
                                      {@(h,e)this.myfunc(h), ...
                                      @(h,e)this.myfunc2(h), ...
                                      @(h,e)this.myfunc2(h)}) ...
                                  ) ...
        );
    end
end

@(h,e)this.myfunc(h)

{@(h,e)this.myfunc(h), ...
@(h,e)this.myfunc2(h), ...
@(h,e)this.myfunc2(h)})
           
@(h,e)(cellfun(@(x)feval(x,h,e), ...
       {cb, ...
        @(h,e)triggerPanel('saveCondition', guidata(h)), ...
        @(h,e)triggerPanel('loadCondition', guidata(h))}))
    
    
    'getfield(guidata(hObject), ''', newField, ''')'